"""Interval Type-2 Fuzzy cluster-head selection.

A Karnik-Mendel interval type-2 fuzzy inference system scores every alive
node's suitability as a cluster head from three inputs (residual energy,
distance to BS, local density), and the top-`k` scorers become CHs.
Karnik, N. N., & Mendel, J. M. (2001), "Centroid of a type-2 fuzzy set,"
Information Sciences, 132(1-4), 195-220, is the standard reference for the
iterative type-reduction algorithm used here; type-2 fuzzy CH scoring
itself follows the general approach common in the WSN clustering
literature (e.g. type-2-fuzzy-logic cluster head election schemes building
on Gupta et al.'s type-1 fuzzy LEACH variants), adapted here to the
specific 27-rule base given below.

`control_model = "centralized"`: the BS computes every node's score and
dictates cluster structure (see `docs/ASSUMPTIONS.md` item 23) -- no node
makes an autonomous CH decision.

Inputs (per alive node, each normalized to [0, 1])
---------------------------------------------------
- E  (residual energy): `net.energy[i] / net.initial_energy[i]`, clipped
  to [0,1] -- normalized against the node's OWN starting energy so this
  still means "fraction of my own budget left" under heterogeneity.
- D  (distance to BS): `net.dist_bs[i] / net.dist_bs.max()` -- normalized
  against the fixed (static, all-node) maximum node-to-BS distance, a
  stable denominator that does not shift as nodes die.
- Dn (local density): count of alive nodes within `cfg.density_radius`
  (excluding itself), normalized by `max(1, n_alive - 1)` (the maximum
  possible neighbour count this round).

Interval Type-2 Gaussian membership functions (uncertain mean)
----------------------------------------------------------------
Three MFs per input, centered at 0.0 / 0.5 / 1.0 across the normalized
[0,1] range (Low/Med/High for E and Dn; Near/Med/Far for D). Each MF is a
"Gaussian with uncertain mean": the mean can be anywhere in
`[c - FOU/2, c + FOU/2]` where `FOU = 0.1` (10% of the [0,1] input range,
per spec), with a FIXED standard deviation `SIGMA = 0.25` (a shape
constant chosen for smooth overlap between adjacent MFs across a [0,1]
domain with 3 evenly spaced centers -- not tuned to this benchmark's
data). This yields the standard upper/lower membership envelope:

    upper(x) = 1                         if m1 <= x <= m2
             = Gaussian(x; m1, SIGMA)     if x < m1
             = Gaussian(x; m2, SIGMA)     if x > m2
    lower(x) = Gaussian(x; m2, SIGMA)     if x <= (m1+m2)/2
             = Gaussian(x; m1, SIGMA)     otherwise

where m1 = c - FOU/2, m2 = c + FOU/2.

The 27-rule base (implemented EXACTLY, reproduced here verbatim)
--------------------------------------------------------------------
Output levels VL/L/M/H/VH, generated by `score = 2*E + (2-D) + Dn` with
levels 0/1/2 per linguistic term, mapped VL(0-1) L(2-3) M(4) H(5-6)
VH(7-8). Energy is double-weighted because it dominates lifetime.

    | E    | D    | Dn=Low | Dn=Med | Dn=High |
    |------|------|--------|--------|---------|
    | Low  | Near | L      | L      | M       |
    | Low  | Med  | VL     | L      | L       |
    | Low  | Far  | VL     | VL     | L       |
    | Med  | Near | M      | H      | H       |
    | Med  | Med  | L      | M      | H       |
    | Med  | Far  | L      | L      | M       |
    | High | Near | H      | VH     | VH      |
    | High | Med  | H      | H      | VH      |
    | High | Far  | M      | H      | H       |

Every rule's firing interval is the interval AND (componentwise min) of
its three antecedent membership intervals; the consequent crisp value used
in type reduction is the MIDPOINT of that output level's score bucket
(VL=0.5, L=2.5, M=4.0, H=5.5, VH=7.5).

Karnik-Mendel type reduction & CH selection
----------------------------------------------
The standard iterative KM algorithm (Karnik & Mendel, 2001) reduces the 27
rule firing intervals + consequents to `[y_l, y_r]`; the node's crisp score
is the midpoint `(y_l + y_r) / 2`. The `k = max(1, round(cfg.p_ch *
n_alive))` highest-scoring alive nodes become CHs. Re-clustering happens
every `cfg.ga_interval` rounds -- the SAME knob and carry-forward semantics
as NSGA-II (`protocols/nsga2.py`): between reclusterings, the last
assignment is reused, dropping dead CHs (members rejoin their nearest
surviving CH, or become self-heads if none survive).

Deviations / notes
-------------------
- All energy accounting and packet sizing is engine-owned, as with every
  protocol here; this module only decides cluster structure.
- `ops_this_round` counts every rule firing (27 per scored node, per spec)
  plus every distance computation (density-radius neighbour comparisons
  and nearest-CH membership assignment).
"""

import math

import numpy as np

from ..network import BS
from .base import ClusterAssignment, Protocol, Transmission

# --- 27-rule base, reproduced verbatim from the spec table above --------
# Indices: [E][D][Dn], E/D/Dn in {0: Low/Near, 1: Med, 2: High/Far}.
RULE_TABLE = [
    # E = Low
    [
        ["L", "L", "M"],    # D = Near
        ["VL", "L", "L"],   # D = Med
        ["VL", "VL", "L"],  # D = Far
    ],
    # E = Med
    [
        ["M", "H", "H"],
        ["L", "M", "H"],
        ["L", "L", "M"],
    ],
    # E = High
    [
        ["H", "VH", "VH"],
        ["H", "H", "VH"],
        ["M", "H", "H"],
    ],
]

LEVEL_VALUE = {"VL": 0.5, "L": 2.5, "M": 4.0, "H": 5.5, "VH": 7.5}

MF_CENTERS = (0.0, 0.5, 1.0)
FOU_DELTA = 0.1
SIGMA = 0.25


def _it2_gaussian(x: float, c: float, delta: float, sigma: float):
    """Interval type-2 Gaussian MF with uncertain mean. Returns
    (lower_membership, upper_membership) for crisp input `x`.
    """
    m1, m2 = c - delta / 2.0, c + delta / 2.0
    if x < m1:
        upper = math.exp(-0.5 * ((x - m1) / sigma) ** 2)
    elif x > m2:
        upper = math.exp(-0.5 * ((x - m2) / sigma) ** 2)
    else:
        upper = 1.0
    if x <= (m1 + m2) / 2.0:
        lower = math.exp(-0.5 * ((x - m2) / sigma) ** 2)
    else:
        lower = math.exp(-0.5 * ((x - m1) / sigma) ** 2)
    return lower, upper


class FuzzyT2Protocol(Protocol):
    name = "fuzzy_t2"
    control_model = "centralized"

    def __init__(self):
        self.reclustered_this_round = False
        self._assignment = ClusterAssignment(ch_ids=[], member_of={})
        self._has_clustered = False

    # ------------------------------------------------------------------
    # Fuzzy scoring
    # ------------------------------------------------------------------
    def _mf_intervals(self, x: float):
        return [_it2_gaussian(x, c, FOU_DELTA, SIGMA) for c in MF_CENTERS]

    def _km_reduce(self, c: np.ndarray, f_lower: np.ndarray, f_upper: np.ndarray, side: str) -> float:
        """Standard iterative Karnik-Mendel type reduction for one side
        ('l' or 'r'). `c` need not be pre-sorted; sorting happens here.
        """
        order = np.argsort(c)
        c_sorted = c[order]
        fl_sorted = f_lower[order]
        fu_sorted = f_upper[order]
        n = len(c_sorted)
        if n == 0:
            return 0.0
        if n == 1:
            return float(c_sorted[0])

        f = (fl_sorted + fu_sorted) / 2.0
        denom = f.sum()
        y = float((f * c_sorted).sum() / denom) if denom > 0 else float(c_sorted.mean())

        for _ in range(100):
            k = int(np.searchsorted(c_sorted, y, side="right") - 1)
            k = max(0, min(k, n - 2))
            if side == "l":
                f_new = np.concatenate([fu_sorted[: k + 1], fl_sorted[k + 1:]])
            else:
                f_new = np.concatenate([fl_sorted[: k + 1], fu_sorted[k + 1:]])
            denom = f_new.sum()
            y_new = float((f_new * c_sorted).sum() / denom) if denom > 0 else y
            if abs(y_new - y) < 1e-9:
                y = y_new
                break
            y = y_new
        return y

    def _node_score(self, e_norm: float, d_norm: float, dn_norm: float) -> float:
        e_mfs = self._mf_intervals(e_norm)    # Low, Med, High
        d_mfs = self._mf_intervals(d_norm)    # Near, Med, Far
        dn_mfs = self._mf_intervals(dn_norm)  # Low, Med, High

        c_list = []
        fl_list = []
        fu_list = []
        for ei in range(3):
            el, eu = e_mfs[ei]
            for di in range(3):
                dl, du = d_mfs[di]
                for dni in range(3):
                    dnl, dnu = dn_mfs[dni]
                    self.ops_this_round += 1  # one rule firing
                    level = RULE_TABLE[ei][di][dni]
                    c_list.append(LEVEL_VALUE[level])
                    fl_list.append(min(el, dl, dnl))
                    fu_list.append(min(eu, du, dnu))

        c = np.array(c_list, dtype=float)
        fl = np.array(fl_list, dtype=float)
        fu = np.array(fu_list, dtype=float)
        y_l = self._km_reduce(c, fl, fu, "l")
        y_r = self._km_reduce(c, fl, fu, "r")
        return (y_l + y_r) / 2.0

    def _score_all_alive(self, net, alive_idx):
        cfg = net.cfg
        n_alive = len(alive_idx)
        alive_arr = np.asarray(alive_idx, dtype=int)

        e_norm = np.clip(net.energy[alive_arr] / net.initial_energy[alive_arr], 0.0, 1.0)

        max_d_bs = float(net.dist_bs.max()) if net.dist_bs.max() > 0 else 1.0
        d_norm = np.clip(net.dist_bs[alive_arr] / max_d_bs, 0.0, 1.0)

        # Local density: count of alive nodes within cfg.density_radius,
        # excluding self. Vectorized over the alive x alive submatrix; ops
        # counts one distance comparison per (i, j) pair considered.
        sub_dist = net.dist[np.ix_(alive_arr, alive_arr)]
        within = sub_dist <= cfg.density_radius
        np.fill_diagonal(within, False)
        self.ops_this_round += int(sub_dist.size)
        density_counts = within.sum(axis=1)
        dn_norm = np.clip(density_counts / max(1, n_alive - 1), 0.0, 1.0)

        scores = np.array([
            self._node_score(float(e_norm[i]), float(d_norm[i]), float(dn_norm[i]))
            for i in range(n_alive)
        ])
        return scores

    # ------------------------------------------------------------------
    # Clustering
    # ------------------------------------------------------------------
    def _recluster(self, net):
        cfg = net.cfg
        alive_idx = np.flatnonzero(net.alive).tolist()
        n_alive = len(alive_idx)
        k = max(1, min(n_alive, round(cfg.p_ch * n_alive)))

        scores = self._score_all_alive(net, alive_idx)
        order = np.argsort(-scores)  # descending
        ch_ids = [int(alive_idx[i]) for i in order[:k]]

        ch_arr = np.array(ch_ids, dtype=int)
        alive_arr = np.array(alive_idx, dtype=int)
        non_ch = alive_arr[~np.isin(alive_arr, ch_arr)]
        member_of = {}
        if len(non_ch) > 0:
            d = net.dist[np.ix_(non_ch, ch_arr)]
            self.ops_this_round += int(d.size)
            nearest_pos = np.argmin(d, axis=1)
            for n, p in zip(non_ch.tolist(), nearest_pos.tolist()):
                member_of[int(n)] = int(ch_arr[p])

        return ClusterAssignment(ch_ids=ch_ids, member_of=member_of)

    def _carry_forward(self, net):
        prev = self._assignment
        alive = net.alive
        surviving_chs = [c for c in prev.ch_ids if alive[c]]
        member_of = {}
        if surviving_chs:
            ch_arr = np.array(surviving_chs, dtype=int)
            for m, c in prev.member_of.items():
                if not alive[m]:
                    continue
                if alive[c]:
                    member_of[m] = c
                else:
                    dists = net.dist[m, ch_arr]
                    nearest = int(ch_arr[int(np.argmin(dists))])
                    member_of[m] = nearest
        return ClusterAssignment(ch_ids=surviving_chs, member_of=member_of)

    # ------------------------------------------------------------------
    # Protocol interface
    # ------------------------------------------------------------------
    def setup_round(self, net, round_idx: int, rng) -> ClusterAssignment:
        cfg = net.cfg
        if not self._has_clustered or round_idx % cfg.ga_interval == 0:
            assignment = self._recluster(net)
            self.reclustered_this_round = True
            self._has_clustered = True
        else:
            assignment = self._carry_forward(net)
            self.reclustered_this_round = False
        self._assignment = assignment
        return assignment

    def route(self, net, assignment: ClusterAssignment, round_idx: int) -> list:
        members_by_ch = {}
        for m, c in assignment.member_of.items():
            members_by_ch.setdefault(c, []).append(m)

        transmissions = []
        for ch in assignment.ch_ids:
            members = sorted(m for m in members_by_ch.get(ch, []) if net.alive[m])
            for slot, m in enumerate(members):
                transmissions.append(
                    Transmission(src=m, dst=ch, kind="data", slot_index=slot, hop_depth=1, originates=True)
                )
            if net.alive[ch]:
                transmissions.append(
                    Transmission(
                        src=ch, dst=BS, kind="data", slot_index=len(members),
                        hop_depth=2, originates=True,
                    )
                )

        assigned_or_ch = set(assignment.ch_ids) | set(assignment.member_of.keys())
        alive_idx = np.flatnonzero(net.alive)
        for n in alive_idx:
            n = int(n)
            if n in assigned_or_ch:
                continue
            transmissions.append(
                Transmission(src=n, dst=BS, kind="data", slot_index=0, hop_depth=1, originates=True)
            )

        return transmissions
